/*
 * AkkaraDB - The all-purpose KV store: blazing fast and reliably durable, scaling from tiny embedded cache to large-scale distributed database
 * Copyright (C) 2026 Swift Storm Studio
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// akkengine/src/cpu/crc32c/CRC32CX86AVX512.cpp
#if defined(__x86_64__) || defined(_M_X64)

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <immintrin.h>

#if defined(__GNUC__) || defined(__clang__)
#  define AKKARADB_TARGET_AVX512 __attribute__((target("avx512f,avx512vl,vpclmulqdq,sse4.2")))
#else
#  define AKKARADB_TARGET_AVX512
#endif

namespace akkaradb::cpu {
    namespace {
        /*
         * VPCLMULQDQ folding constants generated by corsix/fast-crc32 for
         * CRC32C, algorithm avx512Vpclmulqdq/v1e. The same generated family is
         * used by PostgreSQL's AVX-512 CRC32C path.
         */
        #define clmulLo(a, b) (_mm512_clmulepi64_epi128((a), (b), 0x00))
        #define clmulHi(a, b) (_mm512_clmulepi64_epi128((a), (b), 0x11))

        [[nodiscard]] inline uint64_t loadU64(const uint8_t* p) noexcept {
            uint64_t value{};
            std::memcpy(&value, p, sizeof(value));
            return value;
        }

        [[nodiscard]] inline uint32_t loadU32(const uint8_t* p) noexcept {
            uint32_t value{};
            std::memcpy(&value, p, sizeof(value));
            return value;
        }

        [[nodiscard]] inline uint32_t crc32cSse42(uint32_t crc, const uint8_t* p, size_t length) noexcept {
            uint64_t wideCrc = crc;

            while (length >= 8) {
                wideCrc = _mm_crc32_u64(wideCrc, loadU64(p));
                p += 8;
                length -= 8;
            }

            if (length >= 4) {
                wideCrc = _mm_crc32_u32(static_cast<uint32_t>(wideCrc), loadU32(p));
                p += 4;
                length -= 4;
            }

            while (length != 0) {
                wideCrc = _mm_crc32_u8(static_cast<uint32_t>(wideCrc), *p);
                ++p;
                --length;
            }

            return static_cast<uint32_t>(wideCrc);
        }
    } // namespace

    [[nodiscard]] AKKARADB_TARGET_AVX512 uint32_t CRC32C_X86_AVX512(const std::byte* data, size_t length) noexcept {
        if (length == 0) { return 0u; }

        const auto* p = reinterpret_cast<const uint8_t*>(data);
        uint32_t crc = 0xFFFFFFFFu;

        if (length > 256) {
            while (length != 0 && (reinterpret_cast<std::uintptr_t>(p) & 7u) != 0) {
                crc = _mm_crc32_u8(crc, *p);
                ++p;
                --length;
            }

            while ((reinterpret_cast<std::uintptr_t>(p) & 56u) != 0 && length >= 8) {
                crc = static_cast<uint32_t>(_mm_crc32_u64(crc, loadU64(p)));
                p += 8;
                length -= 8;
            }
        }

        if (length >= 64) {
            const uint8_t* const end = p + length;
            const uint8_t* const limit = p + length - 64;
            __m128i z0;

            __m512i x0 = _mm512_loadu_si512(p);
            __m512i y0;
            __m512i k = _mm512_broadcast_i32x4(_mm_setr_epi32(0x740eef02, 0, 0x9e4addf8, 0));

            x0 = _mm512_xor_si512(_mm512_zextsi128_si512(_mm_cvtsi32_si128(static_cast<int>(crc))), x0);
            p += 64;

            while (p <= limit) {
                y0 = clmulLo(x0, k);
                x0 = clmulHi(x0, k);
                x0 = _mm512_ternarylogic_epi64(x0, y0, _mm512_loadu_si512(p), 0x96);
                p += 64;
            }

            k = _mm512_setr_epi32(0x1c291d04, 0, 0xddc0152b, 0, 0x3da6d0cb, 0, 0xba4fc28e, 0, 0xf20c0dfe, 0, 0x493c7d27, 0, 0, 0, 0, 0);
            y0 = clmulLo(x0, k);
            k = clmulHi(x0, k);
            y0 = _mm512_xor_si512(y0, k);
            z0 = _mm_ternarylogic_epi64(
                _mm512_castsi512_si128(y0),
                _mm512_extracti32x4_epi32(y0, 1),
                _mm512_extracti32x4_epi32(y0, 2),
                0x96
            );
            z0 = _mm_xor_si128(z0, _mm512_extracti32x4_epi32(x0, 3));

            crc = static_cast<uint32_t>(_mm_crc32_u64(0, static_cast<uint64_t>(_mm_cvtsi128_si64(z0))));
            crc = static_cast<uint32_t>(_mm_crc32_u64(crc, static_cast<uint64_t>(_mm_extract_epi64(z0, 1))));
            length = static_cast<size_t>(end - p);
        }

        return ~crc32cSse42(crc, p, length);
    }
} // namespace akkaradb::cpu

#undef clmulLo
#undef clmulHi
#undef AKKARADB_TARGET_AVX512

#endif
