if (NOT DEFINED DISKSPD_URL OR DISKSPD_URL STREQUAL "")
    message(FATAL_ERROR "DISKSPD_URL is required")
endif ()
if (NOT DEFINED DISKSPD_ARCH_SUBDIR OR DISKSPD_ARCH_SUBDIR STREQUAL "")
    message(FATAL_ERROR "DISKSPD_ARCH_SUBDIR is required")
endif ()
if (NOT DEFINED DISKSPD_WORK_DIR OR DISKSPD_WORK_DIR STREQUAL "")
    message(FATAL_ERROR "DISKSPD_WORK_DIR is required")
endif ()
if (NOT DEFINED DISKSPD_OUTPUT_DIR OR DISKSPD_OUTPUT_DIR STREQUAL "")
    message(FATAL_ERROR "DISKSPD_OUTPUT_DIR is required")
endif ()

set(DISKSPD_ZIP_PATH "${DISKSPD_WORK_DIR}/DiskSpd.zip")
set(DISKSPD_EXTRACT_DIR "${DISKSPD_WORK_DIR}/extracted")
set(DISKSPD_SOURCE_EXE "${DISKSPD_EXTRACT_DIR}/${DISKSPD_ARCH_SUBDIR}/diskspd.exe")
set(DISKSPD_OUTPUT_EXE "${DISKSPD_OUTPUT_DIR}/diskspd.exe")

file(MAKE_DIRECTORY "${DISKSPD_WORK_DIR}")
file(MAKE_DIRECTORY "${DISKSPD_OUTPUT_DIR}")

if (NOT EXISTS "${DISKSPD_SOURCE_EXE}")
    if (NOT EXISTS "${DISKSPD_ZIP_PATH}")
        file(DOWNLOAD
                "${DISKSPD_URL}"
                "${DISKSPD_ZIP_PATH}"
                SHOW_PROGRESS
                STATUS DISKSPD_DOWNLOAD_STATUS
                TLS_VERIFY ON
        )
        list(GET DISKSPD_DOWNLOAD_STATUS 0 DISKSPD_DOWNLOAD_CODE)
        if (NOT DISKSPD_DOWNLOAD_CODE EQUAL 0)
            list(GET DISKSPD_DOWNLOAD_STATUS 1 DISKSPD_DOWNLOAD_MESSAGE)
            message(FATAL_ERROR "Failed to download DiskSpd: ${DISKSPD_DOWNLOAD_MESSAGE}")
        endif ()
    endif ()

    file(REMOVE_RECURSE "${DISKSPD_EXTRACT_DIR}")
    file(MAKE_DIRECTORY "${DISKSPD_EXTRACT_DIR}")
    file(ARCHIVE_EXTRACT INPUT "${DISKSPD_ZIP_PATH}" DESTINATION "${DISKSPD_EXTRACT_DIR}")
endif ()

if (NOT EXISTS "${DISKSPD_SOURCE_EXE}")
    message(FATAL_ERROR "DiskSpd executable not found after extraction: ${DISKSPD_SOURCE_EXE}")
endif ()

file(COPY_FILE "${DISKSPD_SOURCE_EXE}" "${DISKSPD_OUTPUT_EXE}" ONLY_IF_DIFFERENT)

if (DEFINED DISKSPD_DIST_DIR AND NOT DISKSPD_DIST_DIR STREQUAL "")
    file(MAKE_DIRECTORY "${DISKSPD_DIST_DIR}")
    file(COPY_FILE "${DISKSPD_SOURCE_EXE}" "${DISKSPD_DIST_DIR}/diskspd.exe" ONLY_IF_DIFFERENT)
endif ()
